// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytaasrrlhnbedghnshtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0YWFzcnJsaG5iZWRnaG5zaHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTkwNzMsImV4cCI6MjA2NDc5NTA3M30.Hb8WBCgfYDZCq36xphgr8SkxotiesX1kmUaS17qHU5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});